### ISSUE TITLE
Create Binary Output Prediction Model

### ISSUE THREAD

**Issue by LuckyLaharlTim** [LuckyLaharlTim/pipeline-elevation-project#3]
## Make model predicting if images from #2 are `(1) Safe Vegetation Level` or `(0) Inadequate Vegetation Level` 
- model likely in a Jupyter Notebook
- all requirements needed for ML should be in `requirements_py3##.txt` as of 4/23

----------------------------------------
## 5/3 Update
- Pictures have been uploaded (about 5000) since 5/1
- viewing in ArcGIS is difficult--likely due to extra channel, but can be viewed in python
**View *Modeling/model.ipynb* to get started
requirements were updated with commit https://github.com/LuckyLaharlTim/pipeline-elevation-project/commit/336a0bb4108a215cedc6cbff64fc38c8fecd91be**
- <ins>feel free to change the file name if needed!</ins>
-------------------------------------------------------
## Tasks
- [ ] transferring [channels from different sets to one numpy array](https://stackoverflow.com/questions/41856787/plot-colour-image-from-a-numpy-array-that-has-3-channels) is necessary
- [ ] make label data structure for the pipelines
- [ ] start with model
- [ ] ensure average output predictions can be linked back to single pipeline record (from original shapefile)

**Comment by LuckyLaharlTim** [comment]
Updated task list, @TrevorKap. I will update you (and the associate) when the pictures can be linked to pipeline records in base shapefile.
